spring:
  application:
    name: CipherQuest
  ai:
    openai:
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
      embedding:
        options:
          model: text-embedding-3-small
      api-key: ${OPENAI_API_KEY}
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
  threads:
    virtual:
      enabled: true

application:
  name: '@project.name@'
  version: '@project.version@'

info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
