spring:
  application:
    name: CipherQuest
  ai:
    ollama:
      chat:
        model: llama3
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres

application:
  name: '@project.name@'
  version: '@project.version@'


info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
