spring:
  application:
    name: CipherQuest
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
          keep-alive: 10m
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
  threads:
    virtual:
      enabled: true

application:
  name: '@project.name@'
  version: '@project.version@'


info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
