nameReference:
  - kind: SealedSecret
    fieldSpecs:
      # Deployment references
      - path: spec/template/spec/volumes/secret/secretName
        kind: Deployment
  - kind: Secret
    fieldSpecs:
      - kind: SealedSecret
        path: metadata/name
      - kind: SealedSecret
        path: spec/template/metadata/name
