### POST request to load documents on pgvector

POST http://localhost:8080/rag/load

### POST request with memory id 123

POST http://localhost:8080/chat/123

What happened to the democracy?

### POST request with memory id 123

POST http://localhost:8080/chat/123

Stop controlling the population!


