name: CI github actions

on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots ktlint:check

  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots detekt:check -Ddetekt.config=detekt.yml
